#!/usr/bin/env python3
import argparse
import csv
from pathlib import Path


def load_csv(path):
    with path.open(newline="") as f:
        rows = list(csv.DictReader(f))
    data = {}
    if not rows:
        return data
    for key in rows[0].keys():
        values = []
        for row in rows:
            value = row.get(key, "")
            try:
                values.append(float(value))
            except ValueError:
                values.append(0.0)
        data[key] = values
    return data


def main():
    parser = argparse.ArgumentParser(description="Plot mnCCL cluster time-series metrics.")
    parser.add_argument(
        "--input",
        default="mncc_cluster_timeseries.csv",
        help="CSV generated by NormalNetwork cluster monitor.",
    )
    parser.add_argument(
        "--output",
        default="mncc_cluster_timeseries.png",
        help="Output PNG path.",
    )
    parser.add_argument(
        "--trim-active",
        action="store_true",
        help="Only plot through the last timestamp with active tasks, collectives, or local queue activity.",
    )
    args = parser.parse_args()

    csv_path = Path(args.input)
    data = load_csv(csv_path)
    if not data or "time_ns" not in data:
        raise SystemExit(f"no data found in {csv_path}")

    import matplotlib.pyplot as plt

    if args.trim_active:
        activity_keys = [
            "active_tasks",
            "outstanding_collectives",
            "queued_local_flows",
            "active_local_gpus",
        ]
        last = 0
        for i in range(len(data["time_ns"])):
            if any(data.get(k, [0.0] * len(data["time_ns"]))[i] > 0 for k in activity_keys):
                last = i
        for key in list(data.keys()):
            data[key] = data[key][: last + 1]

    t_ms = [x / 1e6 for x in data["time_ns"]]
    fig, axes = plt.subplots(4, 1, figsize=(12, 10), sharex=True)

    axes[0].plot(t_ms, data.get("expert_fragmentation", []), label="expert fragmentation")
    axes[0].plot(t_ms, data.get("expert_slot_utilization", []), label="expert slot utilization")
    axes[0].plot(t_ms, data.get("gpu_utilization", []), label="gpu memory utilization")
    if "placement_gpu_utilization" in data:
        axes[0].plot(t_ms, data.get("placement_gpu_utilization", []), label="placement GPU coverage")
    axes[0].set_ylabel("ratio")
    axes[0].set_ylim(bottom=0)
    axes[0].legend(loc="best")
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(t_ms, data.get("used_expert_slots", []), label="used expert slots")
    axes[1].plot(t_ms, data.get("free_expert_slots", []), label="free expert slots")
    axes[1].plot(t_ms, data.get("max_free_expert_slots", []), label="max contiguous free slots")
    axes[1].set_ylabel("slots")
    axes[1].legend(loc="best")
    axes[1].grid(True, alpha=0.3)

    axes[2].plot(t_ms, data.get("queued_local_flows", []), label="queued local flows")
    axes[2].plot(t_ms, data.get("active_local_gpus", []), label="active local GPUs")
    axes[2].set_ylabel("count")
    axes[2].legend(loc="best")
    axes[2].grid(True, alpha=0.3)

    axes[3].plot(t_ms, data.get("active_tasks", []), label="active tasks")
    axes[3].plot(t_ms, data.get("outstanding_collectives", []), label="outstanding collectives")
    axes[3].plot(t_ms, data.get("free_slot_variance", []), label="free slot variance")
    axes[3].set_xlabel("simulation time (ms)")
    axes[3].set_ylabel("count / variance")
    axes[3].legend(loc="best")
    axes[3].grid(True, alpha=0.3)

    fig.suptitle("mnCCL Cluster Fragmentation and Load Timeline")
    fig.tight_layout()
    fig.savefig(args.output, dpi=160)


if __name__ == "__main__":
    main()
